#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
if [ -e "shool" ]
then
	echo "school file exists"
	if [ -s "shool" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "shool" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"	
fi
